const EventsFromWebView = {
  LOGIN: 'login',
  EXPIRED_TOKEN: 'expiredToken',
  LOG_OUT: 'logout',
  PLAY_SONG: 'goToPlay',
  MANAGER_HEADPHONE: 'manageHeadphone',
  CHANGE_HEADPHONE: 'listeningHeadphone',
  BACK_PRESS: 'backPress',
  IS_CORRECT_PASS_CODE: 'isCorrectPassCode',
  CHECK_MINI_PLAYER: 'checkMiniPlayer',
  EXIT_APP: 'exitApp',
  SAVE_PASS_CODE: 'savePasscode',
  SAVE_PRIVATE_KEY: 'savePrivateKey',
  COVER_NATIVE_DISPLAY: 'coverNativeDisplay',
  RELEASE_NATIVE_DISPLAY: 'releaseNativeDisplay',
  CHECK_PASS_CODE: 'checkPasscode',
  CHARGE_HEADPHONE: 'chargeHeadphone',
  REQUEST_PRIVATE_KEY: 'getPrivateKey',
  SEND_PRIVATE_KEY: 'sendPrivateKey',
  NO_BOTTOM_MENU: 'setNoBottomMenu',
  SHOW_ALERT: 'showAlert',
  SHOW_LOG: 'showLog',
  SETUP_WALLET: 'setupWallet',
  DETAIL_WALLET: 'detailWallet',
  SEND_ACCESS_TOKEN: 'sendAccessToken',
  IS_PLAYING: 'isPlaying',
  BACK_TO_PLAYER: 'backToPlayer',
  SEND_INFO_CURRENT_SONG: 'sendInfoCurrentSong',
  SEND_PLAY_SONG: 'sendSongPlay',
  REQUEST_CURRENT_SONG_INFO: 'requesCurrentSongInfo',
  REQUEST_NAVIGATION: 'requsetNavigation',
  WRITE_CLIPBOARD: 'writeClipboard',
  READ_CLIPBOARD: 'readClipboard'
}

export default EventsFromWebView